jobs:
    include:
        - stage: Test
          language: node_js
          node_js: '12'
          install: npm ci || cat /home/travis/.npm/_logs/*-debug.log

        - stage: Deploy
          language: bash
          script: skip
          deploy:
              - provider: script
                script: bash deploy.sh Steve_Deploy $API_TOKEN
                on:
                    branch: master
                    repo: Ionaru/steve

env:
    global:
        - secure: m1RkF26LmpasSovtc4mkbBClwCJ2sobwaFOxooYBV1xi0jk3JfibcIva8qppXMF1hhPAajUNrdXEeryNJO9255E8vMhzKFSV5o3KPJ6rqu3uDE8BMWQ91R9cYwhrpWiO0ornmpmHwRe6w2fJYy8QJT1xC+2R4kER5warMsXpk8PvGA+Fu3hNLksDYyRRtvYgdzQaHNjH2airlsD+/fWnmRleGF+tG3HSSmWD9RPSTJXUggDIfnMzVAwCnRqVkoHhWL7E1B5DSNnM2mObZ36ASxuBkDN5/h7tAIBVg3pkuIv8pjPMNG4iI9aRwQlrwfh9FNkMWMjP9Tm2NN4vvJcaOBfCySJz5ZlezOy21zyNjevStkv4dhk8JeCBvZwwudGqsP2lNfWZ0KNfzFqxd1lZRm2KiaSeHk7y+1+Idxg7dCEuMW1CUFkv+wlpbDn9RSGnq/msL6mmHKvcZh5p1vRcpCUU+hX52BO+FUnmsQZIYV2RSz5haJALJaBgWmVjN85l3fLNU4RyLNRAEeGYMNLqusUzwVBYlN9Vov4R4bAiPARI9LwhGMtJYRHWNt1gVxp5IOEaPkHKnNlVRMwb52nkrFujyk0E0LcM6+bpjUpqr+4D60gfidsmUNQTv3pqToB+krBmXPlImKXkdLtdMn66lomHpjbVieIWOV/cQiC0V8k=
        - secure: sasEEw7/Bm9GtndKxx+BeXmvRaafG+sLfQnDlbOxMvX/MQwDOx3QsI7zwt73F96atxAn5gPOE4cQXEj0CCW+f0du8GIGcWuePF+w/fC4M02PyP9bTZdh476INj/LrowE1ClccmvXv4dIBc3yg6zLQnxno792j7igIM9u8/7hgiTIHMSPquk2DG36IzI+tiBVYUMFJZScLqRF66Sxd6Y8YtQLhD11nU4d7IIOgc4gu7gArd8llNE8wCQoms0uO9Z/uetqc2tcnbvRx8U1ZcqQqXdqFNqUXuh0AIjN6sgdNtLWEMulKCpNe3Ns6kKUvFQ8hnBzPVnzNQFxWcOKHryCPOnDaFX+hiGmn9kSnzLn8Vgn6nhBdTINKxy+WPCU5vhWyUoam8x6DkgZwE8A5i0754ssyQhvvl5bozSn5DdJ9Vqiy9JPqL37L1hp0dkdhMAXgi7XriaboXg6GtoaHDNvx1nB1TLFu+9aQ+RHyRzGDXbq4gK1wjo6P5OJM6JIY0PLaUB/9KXb0iJh+NShG3zexoduH8Q/Wez+N6vu5cqvshm6moj7qc8gtN/gu+Qy8cYAcWYwkoRDXqyE65eXFHVUtd6uoeSpIqMDVlE7m9S5tk3BU23B1nUPrePUBjXSAJ4GXDyD/S3dGGW/dLK0yve1QOkJ70oV/VSGAomHX9k67w4=
